# Python tutorial

summary of CS228 Python Tutorial by Volodymyr Kuleshov and Isaac Caswell

In [1]:
import mlp

In [2]:
def quicksort (arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr)/2]
    left = [x for x in arr if x< pivot]
    middle = [x for x in arr if x== pivot]
    right = [x for x in arr if x> pivot]
    return quicksort(left) + middle + quicksort(right)

In [3]:
print quicksort([3,6,8,10,1,2,1])

[1, 1, 2, 3, 6, 8, 10]


## Basic data types

#### Numbers

In [4]:
x = 4
print x, type(x)

4 <type 'int'>


In [5]:
y =3
print y**y

27


In [6]:
t,f = True, False

In [7]:
print type(t), type(f)

<type 'bool'> <type 'bool'>


##### Operations

In [8]:
print t and f
print t or f
print not t
print t != f

False
True
False
True


In [9]:
len('hello')

5

In [10]:
s = 'hello'

In [11]:
print s.capitalize()
print s.upper()
print s.rjust(7)
print s.center(7)
print s.replace('l','(ell)')

Hello
HELLO
  hello
 hello 
he(ell)(ell)o


### Containers

#### List
array but resizeable 

In [12]:
xs =[3, 1,2]
print xs, xs[2]
print xs[0:3]
print xs[-1]

[3, 1, 2] 2
[3, 1, 2]
2


In [13]:
xs[2]='foo'
print xs

[3, 1, 'foo']


In [14]:
xs.append('bar') #add a new element to the end of the list
print xs

[3, 1, 'foo', 'bar']


In [15]:
x = xs.pop()
print x, xs

bar [3, 1, 'foo']


## Slicing
to access sublist


In [16]:
nums = range(5)
print nums
print nums[0:5]
print nums[2:4]
print nums[2:]
print nums[:2]
print nums[:]
nums[2:4]=[8,9]
print nums

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 8, 9, 4]


## Loops


In [17]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print '#%d: %s' %(idx +1, animal)

#1: cat
#2: dog
#3: monkey


#### List comprehensions:
transform one type of data into another

In [18]:
nums =[0,1,2,3,4]
squares = []
for x in nums:
    squares.append(x**2)
print squares

[0, 1, 4, 9, 16]


In [19]:
nums = [0,1,2,3,4]
squares=[x**2 for x in nums]
print squares

[0, 1, 4, 9, 16]


with conditions

In [20]:
nums = [0,1,2,3,4]
even_squares = [x**2 for x in nums if x%2 ==0]
print even_squares

[0, 4, 16]


### Dictionaries
a dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript

In [21]:
d={'cat': 'cute', 'dog': 'furry'}
print d['cat']
print 'cat' in d

cute
True


In [22]:
d['fish']='wet'
print d['fish']

wet


In [23]:
print d['monkey']

KeyError: 'monkey'

In [24]:
print d.get('monkey','N/A')
print d.get('fish','N/A')

N/A
wet


In [25]:
del d['fish']

In [26]:
print d.get('fish','N/A')

N/A


In [27]:
d={'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print 'A %s has %d legs' %(animal, legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


In [28]:
d={'person': 2,'cat': 4, 'spider': 8}
for animal, legs in d.iteritems():
    print 'A %s has %d legs' %(animal, legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


dictionary comprehensions

In [29]:
nums = [0,1,2,3,30]
y = [5,6,7,8,9]
even_num_to_square = {x: y[nums.index(x)] for x in nums}
print even_num_to_square

{0: 5, 1: 6, 2: 7, 3: 8, 30: 9}


### Sets
unordered collection of distinct elements

In [30]:
animals = {'cat', 'dog'}
print 'cat' in animals
print 'fish' in animals
print animals

True
False
set(['dog', 'cat'])


In [31]:
animals.add('fish')
print 'fish' in animals
print len(animals), animals

True
3 set(['fish', 'dog', 'cat'])


In [32]:
animals.add('cat')
print len(animals), animals
animals.remove('cat')
print len(animals)

3 set(['fish', 'dog', 'cat'])
2


In [33]:
animals = {'cat','dog','fish'}
for k, animal in enumerate(animals):
    print (k)
    print '#%d: %s' %(k+1, animal)

0
#1: fish
1
#2: dog
2
#3: cat


Comprehensions

In [34]:
from math import sqrt
print {int(sqrt(x))for x in range(30)}

set([0, 1, 2, 3, 4, 5])


In [35]:
sqrt(30)

5.477225575051661

### Tuples
A tuple is in many ways similar to a list. tuplets cna be used as keys in dictionaries

In [36]:
d = {(x, x+1): x for x in range(10)}
t = (5, 6) #tuple
print type (t)
print d[t]
print d[(1,2)]

<type 'tuple'>
5
1


In [37]:
d

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

In [38]:
t[0]=1

TypeError: 'tuple' object does not support item assignment

### Functions
python functions are defined using the def keyword

In [39]:
def sign(x):
    if x>0:
        return 'positive'
    elif x <0:
        return 'negative'
    else:
        return 'zero'
for x in [-1, 0, 1]:
    print sign(x)

negative
zero
positive


keyword arguments

In [40]:
def hello(name, loud=False):
    if loud:
        print 'HELLO, %s' %name.upper()
    else:
        print 'Hello, %s!' %name
        

In [41]:
hello('bob')
hello('fred', loud=True)

Hello, bob!
HELLO, FRED


### Classes

In [42]:
class Greeter:
    #constructor
    def __init__(self, name):
        self.name = name #Create an instance variable
    
    #instance method
    def greet(self, loud=False):
        if loud:
            print 'HELLO %s!' % self.name.upper()
        else:
            print 'Hello, %s' % self.name
g = Greeter('bobob')
g.greet()
g.greet(loud=True)

Hello, bobob
HELLO BOBOB!


# Numpy

In [43]:
import numpy as np

In [44]:
a = np.array([1,2,3])
print type(a), a.shape, a[0], a[1], a[2]
a[0] = 5
print a[0]

<type 'numpy.ndarray'> (3,) 1 2 3
5


In [45]:
b = np.array([[1,2,3],[4,5,6]])
print b

[[1 2 3]
 [4 5 6]]


In [46]:
print b.shape
print b[0,0], b[0,1], b[1,0]

(2, 3)
1 2 4


In [47]:
a = np.zeros((2,2))
print a

[[ 0.  0.]
 [ 0.  0.]]


In [48]:
b = np.ones((1,2))
print 'esto es', b
c = np.full((2,2),7)
print c

esto es [[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]


/Users/hanzcuevas/miniconda2/envs/mlp/lib/python2.7/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [49]:
e = np.random.random((2,2))

In [50]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print b

[[2 3]
 [6 7]]


In [51]:
print a[0,1]
b[0, 0]=77
print a[0,1]

2
77


In [52]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [53]:
row_r1=a[1,:]
row_r2 = a[1:2,:]
row_r3 = a[[1],:]
print row_r1, row_r1.shape
print row_r2, row_r2.shape
print row_r3, row_r3.shape

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [54]:
range(4)

[0, 1, 2, 3]

In [55]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])

In [56]:
print np.reshape(v,(3,1))*w

[[ 4  5]
 [ 8 10]
 [12 15]]


In [57]:
import matplotlib.pyplot as plt

In [59]:
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)
plt.plot(x,y)

In [2]:
np -- help

NameError: name 'np' is not defined

In [7]:
import numpy as np
help(np.all)

Help on function all in module numpy.core.fromnumeric:

all(a, axis=None, out=None, keepdims=False)
    Test whether all array elements along a given axis evaluate to True.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical AND reduction is performed.
        The default (`axis` = `None`) is to perform a logical AND over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.
        It must have the same shape as the expected output and its
        type is preserved (e.g., if ``dtype